FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
        libpng-dev \
        libjpeg-dev \
        libwebp-dev \
        libfreetype6-dev \
        msmtp \
    && docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype \
    && docker-php-ext-install -j"$(nproc)" gd mysqli pdo pdo_mysql \
    && rm -rf /var/lib/apt/lists/*

COPY uploads.ini /usr/local/etc/php/conf.d/uploads.ini
COPY mail.ini /usr/local/etc/php/conf.d/mail.ini
COPY msmtprc /etc/msmtprc
RUN chmod 644 /etc/msmtprc

WORKDIR /var/www/html
