version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www/html:/var/www/html
    ports:
      - 90:80
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=klein
      - MYSQL_USER=trindade
      - MYSQL_PASSWORD=confirma
